name: Build onepage application

on:
    push:
        branches:
            - master
            
jobs:
    deploy:
        name: Deploy application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                ref: master
            - name: Create node environment
              uses: actions/setup-node@v2
              with: 
                node-version: 14.x
            - name: Install packages and build application
              run: |
                npm i
                gulp build
                cp CNAME dist/CNAME
            - name: Deploy
              uses: s0/git-publish-subdir-action@master
              env:
                REPO: self
                BRANCH: gh-pages
                FOLDER: dist
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}